import './globals.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import React from 'react';

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Utiliser .className garantit que next/font applique la font-family */}
      <body className={`${jetBrainsMono.className} antialiased min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
